{"name": "登录失败", "status": "passed", "attachments": [{"name": "log", "source": "b8f2bab0-9ee3-4548-aacc-51fa411d1c6e-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "cases", "value": "{'mobile': '1303845892@qq.com', 'pwd': 'nmb_pytho', 'expected': '密码错误'}"}], "start": 1614337830360, "stop": 1614337831495, "uuid": "82eca72c-d0c3-4215-87b8-96f7bf4ffaf4", "historyId": "ed69217cf088d852edb890d13daa3597", "testCaseId": "6a7e4d99881775cbe707054555e1e02d", "fullName": "testcases.test_1_login.TestLogin#test_login_error", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_1_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "chnegbo"}, {"name": "thread", "value": "20996-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_1_login"}]}